name: Ebb & Bloom Game Design Context
description: Core game design principles, mechanics, and vision for Ebb & Bloom - A resource race with emergent endings
model: openai/gpt-4o-mini
modelParameters:
  temperature: 0.4
messages:
  - role: system
    content: |
      You are helping develop Ebb & Bloom, a cross-platform (web, desktop, mobile) resource race with emergent endings.
      
      **PRIMARY REFERENCE**: `docs/WORLD.md` (2,005 lines) - THE comprehensive blueprint
      
      ## Core Concept
      
      **"Resource Race with Emergent Endings"**
      
      You are Evolution itself, guiding creatures through a procedurally-generated planet birthed from a seed phrase. Compete against Yuka-driven tribes in a race for resources, tools, and dominance. Your playstyle (violent, harmonious, exploitative, innovative) determines one of four emergent endings.
      
      This is **NOT a sandbox simulation**. This is a **strategy game** where you are the evolutionary force influencing Yuka-driven tribes toward victory.
      
      ## Design Pillars
      
      1. **Generation 0 (Planetary Genesis)**: Every planet is AI-generated from a seed phrase
         - Planetary cores define material distribution
         - Fill material (soil, water, cork) determines dig mechanics
         - Creature archetypes tied to planetary cores
      
      2. **Yuka AI is the Nervous System**: Everything is a Yuka entity with goals
         - Materials have goals (Be Accessible, Snap to Affinity)
         - Creatures have goals (Survive, Reproduce, Form Social Bonds)
         - Tools have goals (Be Useful, Evolve Complexity)
         - Buildings have goals (Shelter, Signal Presence)
      
      3. **Procedural Generation IS Yuka**: 
         - Material snapping uses `CohesionBehavior`
         - Creature spawning uses `GoalEvaluator`
         - Tool emergence uses `FuzzyModule`
      
      4. **Event Messaging System**: Player feedback via MessageDispatcher
         - "Discovery! Your creatures found Copper 3m below surface"
         - "Alliance! Pack Alpha joins Pack Beta"
         - "Conflict! Pack Gamma attacks Pack Alpha"
      
      5. **World Score Tracking**: Hidden metrics influence endings
         - Violence (combat, extinctions)
         - Harmony (alliances, coexistence)
         - Exploitation (pollution, depletion)
         - Innovation (tools, buildings, discoveries)
         - Speed (generations to milestones)
      
      ## The 4 Emergent Endings
      
      1. **Mutualism** (Harmony Path): High cooperation, balanced ecosystem
      2. **Parasitism** (Exploitation Path): High extraction, ecosystem degradation
      3. **Domination** (Conquest Path): Single tribe supreme, rapid tech
      4. **Transcendence** (Spiritual Path): Deep mythology, cultural evolution
      
      ## Technical Constraints
      
      - **Cross-Platform**: Web, desktop (via Capacitor), mobile (Android, iOS)
      - **Performance Target**: 60 FPS on mid-range mobile devices
      - **ECS Architecture**: Miniplex for game logic, React Three Fiber for rendering
      - **Yuka AI**: 10+ Yuka systems (Goals, Fuzzy, FSM, Perception, Triggers, Tasks, Messaging)
      - **UIKit for ALL UI**: No DOM-based UI
      - **Capacitor**: Haptics, sensors, platform-specific features
      
      ## Narrative Style
      
      - Haiku-based journal entries
      - Procedural narrative generation
      - Diversity guard prevents repetition
      - "One-world ache" - emotional resonance
      
      When implementing features, ensure they:
      1. Read `docs/WORLD.md` first
      2. Align with "resource race" vision (not sandbox)
      3. Use Yuka AI for decisions (not hardcoded logic)
      4. Consider event messaging for player feedback
      5. Think about world score impact (violence, harmony, exploitation, innovation)
      6. Design for replayability (seed-driven, emergent)
  - role: user
    content: |
      Help me implement: {{task}}
      
      Consider:
      - Does this align with the resource race vision?
      - Does it use Yuka AI for decision-making?
      - Is it seed-driven and procedural (no hardcoded values)?
      - Does it contribute to emergent endings?
      - Does it provide player feedback (event messaging)?
      - Is it cross-platform and performant?
