# Process Compose Configuration
# Run multiple development processes in parallel

version: '0.5'

processes:
  # Backend API Server
  dev-backend:
    command: "cd packages/backend && pnpm dev"
    working_dir: "."
    restart: "on-failure"
    depends_on:
      - typecheck-backend

  # Frontend Dev Server
  dev-frontend:
    command: "cd packages/simulation && pnpm dev"
    working_dir: "."
    restart: "on-failure"
    depends_on:
      - typecheck-frontend

  # Type Checking
  typecheck-backend:
    command: "cd packages/backend && pnpm exec tsc --noEmit --watch"
    working_dir: "."
    restart: "on-failure"

  typecheck-frontend:
    command: "cd packages/simulation && pnpm exec tsc --noEmit --watch"
    working_dir: "."
    restart: "on-failure"

  # Test Watcher
  test-watch:
    command: "cd packages/backend && pnpm test:watch"
    working_dir: "."
    restart: "on-failure"

  # E2E Tests (Backend)
  test-e2e-backend:
    command: "cd packages/backend && pnpm test:e2e"
    working_dir: "."
    restart: "never"

  # E2E Tests (Frontend - Playwright)
  test-e2e-frontend:
    command: "cd packages/simulation && pnpm test:e2e"
    working_dir: "."
    restart: "never"
    depends_on:
      - dev-backend
      - dev-frontend

  # Gen Pipeline
  gen-archetypes:
    command: "cd packages/gen && pnpm cli archetypes"
    working_dir: "."
    restart: "never"
    env:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"

  gen-quality:
    command: "cd packages/gen && pnpm cli quality"
    working_dir: "."
    restart: "never"

  gen-docs:
    command: "cd packages/gen && pnpm cli documentation"
    working_dir: "."
    restart: "never"
