# Process Compose Configuration
# Unified game package - single dev server
# 
# To access from your phone:
# 1. Find your computer's IP: ifconfig | grep "inet " | grep -v 127.0.0.1
# 2. Access game: http://<your-ip>:5173
# 
# Make sure your phone is on the same WiFi network!

version: '0.5'

processes:
  # Unified Game Package (Frontend + Backend in one)
  dev-game:
    command: "cd packages/game && pnpm dev --host"
    working_dir: "."
    restart: "on-failure"
    readiness_probe:
      http:
        path: /
        port: 5173
        initial_delay_seconds: 5
        period_seconds: 2
        timeout_seconds: 3

  # Type Checking
  typecheck-game:
    command: "cd packages/game && pnpm exec tsc --noEmit --watch"
    working_dir: "."
    restart: "on-failure"

  # Test Watcher
  test-watch:
    command: "cd packages/game && pnpm test:watch"
    working_dir: "."
    restart: "on-failure"

  # E2E Tests (Playwright)
  test-e2e:
    command: "cd packages/game && pnpm test:e2e"
    working_dir: "."
    restart: "never"
    depends_on:
      - dev-game

  # Gen Pipeline
  gen-archetypes:
    command: "cd packages/gen && pnpm cli archetypes"
    working_dir: "."
    restart: "never"
    env:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"

  gen-quality:
    command: "cd packages/gen && pnpm cli quality"
    working_dir: "."
    restart: "never"

  gen-docs:
    command: "cd packages/gen && pnpm cli documentation"
    working_dir: "."
    restart: "never"
