# Ebb & Bloom - Process Orchestration
# 
# Start all services with: process-compose up
# Or use pnpm commands in root package.json
#
# Architecture:
# 1. backend  - Game logic REST API (port 3001)
# 2. frontend - React + Three.js (port 5173)
# 3. cli      - CLI client (connects to backend)

version: "0.5"

processes:
  # Backend API Server
  backend:
    command: "pnpm --filter @ebb/backend dev"
    working_dir: "."
    availability:
      restart: "on_failure"
      max_restarts: 5
    readiness_probe:
      http_get:
        host: "localhost"
        port: 3001
        path: "/health"
      initial_delay_seconds: 2
      period_seconds: 1
      timeout_seconds: 1
      success_threshold: 1
      failure_threshold: 3
    
  # Frontend Development Server
  frontend:
    command: "pnpm --filter @ebb/frontend dev"
    working_dir: "."
    depends_on:
      backend:
        condition: process_healthy
    availability:
      restart: "on_failure"
      max_restarts: 5
    readiness_probe:
      http_get:
        host: "localhost"
        port: 5173
        path: "/"
      initial_delay_seconds: 5
      period_seconds: 2
      timeout_seconds: 2
      success_threshold: 1
      failure_threshold: 3
  
  # CLI (manual start, not auto-started)
  # cli:
  #   command: "pnpm --filter @ebb/cli dev"
  #   working_dir: "."
  #   depends_on:
  #     backend:
  #       condition: process_healthy
